"""added last updated date

Revision ID: 116609a6d9a7
Revises: f037b50afd37
Create Date: 2024-10-08 20:58:36.342980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116609a6d9a7'
down_revision = 'f037b50afd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('last_updated_date')

    # ### end Alembic commands ###
