"""empty message

Revision ID: 42d3ce8838d4
Revises: 
Create Date: 2024-10-02 21:17:38.699744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42d3ce8838d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_settings',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OpeningTime', sa.Time(), nullable=False),
    sa.Column('ClosingTime', sa.Time(), nullable=False),
    sa.Column('TradingDays', sa.String(length=50), nullable=False),
    sa.Column('Holidays', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('stocks',
    sa.Column('StockID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CompanyName', sa.String(length=100), nullable=False),
    sa.Column('Ticker', sa.String(length=10), nullable=False),
    sa.Column('Volume', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('StockID'),
    sa.UniqueConstraint('Ticker')
    )
    op.create_table('user',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('PasswordHash', sa.String(length=128), nullable=False),
    sa.Column('CashBalance', sa.Float(), nullable=True),
    sa.Column('Role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('order',
    sa.Column('OrderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('StockID', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=10), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['StockID'], ['stocks.StockID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('portfolio',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('StockID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['StockID'], ['stocks.StockID'], ),
    sa.PrimaryKeyConstraint('UserID', 'StockID')
    )
    op.create_table('transaction',
    sa.Column('TransactionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('StockID', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=10), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['StockID'], ['stocks.StockID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('TransactionID')
    )
    op.drop_table('Order')
    op.drop_table('Portfolio')
    op.drop_table('Transaction')
    with op.batch_alter_table('Stocks', schema=None) as batch_op:
        batch_op.drop_index('Ticker')

    op.drop_table('Stocks')
    op.drop_table('MarketSettings')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('Email')
        batch_op.drop_index('Username')

    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FullName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('PasswordHash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('CashBalance', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('Role', mysql.ENUM('customer', 'admin'), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index('Username', ['Username'], unique=True)
        batch_op.create_index('Email', ['Email'], unique=True)

    op.create_table('MarketSettings',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('OpeningTime', mysql.TIME(), nullable=False),
    sa.Column('ClosingTime', mysql.TIME(), nullable=False),
    sa.Column('TradingDays', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('Holidays', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Stocks',
    sa.Column('StockID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CompanyName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Ticker', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('Volume', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('StockID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Stocks', schema=None) as batch_op:
        batch_op.create_index('Ticker', ['Ticker'], unique=True)

    op.create_table('Transaction',
    sa.Column('TransactionID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('StockID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Type', mysql.ENUM('buy', 'sell'), nullable=False),
    sa.Column('Quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('Timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['StockID'], ['Stocks.StockID'], name='Transaction_ibfk_2'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name='Transaction_ibfk_1'),
    sa.PrimaryKeyConstraint('TransactionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Portfolio',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('StockID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['StockID'], ['Stocks.StockID'], name='Portfolio_ibfk_2'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name='Portfolio_ibfk_1'),
    sa.PrimaryKeyConstraint('UserID', 'StockID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Order',
    sa.Column('OrderID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('StockID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Type', mysql.ENUM('buy', 'sell'), nullable=False),
    sa.Column('Quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Status', mysql.ENUM('pending', 'executed', 'cancelled'), nullable=False),
    sa.Column('Timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['StockID'], ['Stocks.StockID'], name='Order_ibfk_2'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name='Order_ibfk_1'),
    sa.PrimaryKeyConstraint('OrderID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('transaction')
    op.drop_table('portfolio')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('stocks')
    op.drop_table('market_settings')
    # ### end Alembic commands ###
