"""added holidays table

Revision ID: a99a9707099c
Revises: e7af25618039
Create Date: 2024-10-09 13:33:29.765377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99a9707099c'
down_revision = 'e7af25618039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday',
    sa.Column('holiday_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('holiday_id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holiday')
    # ### end Alembic commands ###
