"""empty message

Revision ID: cc4a2053d8c9
Revises: 
Create Date: 2024-10-03 20:59:37.065625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc4a2053d8c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('StockID')
        batch_op.drop_index('UserID')
        batch_op.drop_column('time_stamp')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index('StockID')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('buy', 'sell', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index('StockID')
        batch_op.drop_index('UserID')
        batch_op.drop_column('time_stamp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('cash_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('customer', 'admin', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('customer', 'admin', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)
        batch_op.alter_column('cash_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', mysql.DATETIME(), nullable=False))
        batch_op.create_index('UserID', ['user_id'], unique=False)
        batch_op.create_index('StockID', ['stock_id'], unique=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('buy', 'sell', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index('StockID', ['stock_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', mysql.DATETIME(), nullable=False))
        batch_op.create_index('UserID', ['user_id'], unique=False)
        batch_op.create_index('StockID', ['stock_id'], unique=False)

    # ### end Alembic commands ###
