"""add daily high and low

Revision ID: f037b50afd37
Revises: 555e6569b645
Create Date: 2024-10-08 20:15:28.793075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f037b50afd37'
down_revision = '555e6569b645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_high', sa.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('daily_low', sa.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('daily_low')
        batch_op.drop_column('daily_high')

    # ### end Alembic commands ###
